### ISSUE TITLE
false timestamps in sick_s300 laser message

### ISSUE THREAD

**Issue by NadiaHG** [4am-robotics/cob_driver#120]
@ipa-josh: we tested your modifications successfully on cob4-1 with hydro. We can display a single laser message in rviz.

But running the laser scanners together with other ROS nodes the timestamps don't fit together. the sick timestamp is ~55061077 sec in the past. Looking at the code there's some strange timestamp handling. Can you please clarify or fix to the current ROS timestamp.

**Comment by floweisshardt** [comment]
tested on cob4-1: OK
