### ISSUE TITLE
separate message files out into standalone message packages

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_driver#134]
e.g. messages in cob_sound (currently cob_script_server depends on cob_driver only due to messages in cob_sound)

**Comment by mgruhler** [comment]
when you are on it, maybe also but the launch files in cob_robots?
- cob_sound
- cob_voltage_control
- cob_cam3d_throttle

**Comment by fmessmer** [comment]
I guess all these issues could be tackled when re-structuring cob_hardware_conifg wrt to separation of X_driver.yaml and X_controller.yaml.

Then also:
- move cob_driver-launch files to cob_robots
- move cob_driver-yaml files to cob_robots
- separate message definitions
  Shall we have a separate repo for messages, cob_srvs, brics_actuator?

**Comment by floweisshardt** [comment]
messages
./cob_relayboard/msg/EmergencyStopState.msg
./cob_phidgets/msg/DigitalSensor.msg
./cob_phidgets/msg/AnalogSensor.msg
./cob_light/msg/LightMode.msg

services
./cob_trajectory_controller/srv/SetFloat.srv
./cob_footprint_observer/srv/GetFootprint.srv
./cob_camera_sensors/srv/GetTOFImages.srv
./cob_camera_sensors/srv/AcquireCalibrationImages.srv
./cob_sound/srv/SayText.srv
./cob_base_drive_chain/srv/ElmoRecorderConfig.srv
./cob_base_drive_chain/srv/ElmoRecorderReadout.srv
./cob_phidgets/srv/SetDigitalSensor.srv
./cob_phidgets/srv/SetDataRate.srv
./cob_phidgets/srv/SetTriggerValue.srv
./cob_light/srv/SetLightMode.srv

actions
./cob_sound/action/Say.action
./cob_light/action/SetLightMode.action

**Comment by floweisshardt** [comment]
done
