### ISSUE TITLE
cob_base_drive_chain or cob_undercarriage_control: if velocity twist message has NaN the wheels are uncontrollably rotate

### ISSUE THREAD

**Issue by destogl** [4am-robotics/cob_driver#171]
If velocity twist message has some of the values NaN this value is not filtered out but rather the wheels are starting uncontrollably rotate (around steering axis) and platform shuts down (probably because of to high current). This case should be avoided by checking the input values by corresponding components.

**Comment by floweisshardt** [comment]
@destogl  thanks for pointing that out. Do you know which component was sending the NaN twist? That would be important to fix too.

**Comment by destogl** [comment]
It was my component, it was a bug during develpement.

**Comment by destogl** [comment]
Since is fixed I'll close it.
