### ISSUE TITLE
cob_light (stageprofi): LEDs are flickering if using breath mode

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_driver#182]
this happens e.g. for 
mode = 3
frequency = 20

could be related to the way the messages are published. Probably solving together with #181

**Comment by floweisshardt** [comment]
comment from @ipa-bnm: set all LEDs with one dmx message for predefined modes (1...5).

we only need to set individual ids, if colors[] array is set.

**Comment by thiagodefreitas** [comment]
@ipa-fmw Seems to be a know problem with our DMX setup. We currently need
to write them sequentially into the serial. From the feedback from the
Openlighting people, this seems to be a bug. They are investigating the
problem themselves and I would prefer to wait for them.

**Comment by floweisshardt** [comment]
solved through @ipa-bnm in https://github.com/ipa320/cob_driver/pull/184
