### ISSUE TITLE
document mimic in ROS wiki

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_driver#186]

**Comment by floweisshardt** [comment]
should be a list of all available modes with screenshots

**Comment by floweisshardt** [comment]
list with final names: http://wiki.ros.org/cob_mimic (still missing screenshots, @ipa-nhg can you add that please?)

**Comment by NadiaHG** [comment]
Done! http://wiki.ros.org/cob_mimic

**Comment by floweisshardt** [comment]
looks good.
