### ISSUE TITLE
cob_light_sim: catkin build errors

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_driver#212]
message generation is not triggered before building sources.

Error log:
In file included from /u/fmw/git/care-o-bot/src/cob_driver/cob_light_sim/src/qnode.cpp:18:0:
/u/fmw/git/care-o-bot/src/cob_driver/cob_light_sim/src/../include/cob_light_sim/qnode.hpp:24:38: fatal error: cob_light/ColorRGBAArray.h: No such file or directory
 #include <cob_light/ColorRGBAArray.h>

**Comment by fmessmer** [comment]
see https://github.com/ipa320/cob_driver/pull/213#discussion-diff-27900867

**Comment by floweisshardt** [comment]
outdated
superceeded by #220 and #221
