### ISSUE TITLE
[cob_light] Handling `sim_enabled` param in simulation

### ISSUE THREAD

**Issue by fmessmer** [4am-robotics/cob_driver#236]
See my comments about "Warning B" in https://github.com/ipa320/cob_simulation/issues/87#issuecomment-132086878

So far, we are using the same yaml for simulation and real hardware. This leads to the following warning: 

> [ WARN] [1439833261.548182269]: Serial connection on /dev/ttyLed failed.

In that yaml `sim_enabled` is set to false...thus, in simulation you cannot actually use `sim_enabled`

Maybe we should make it a private parameter that can be set via launch file argument in https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/drivers/light.launch?

@ipa-bnm what do you think?

**Comment by fmessmer** [comment]
As `sim_enabled already is a private parameter....https://github.com/ipa320/cob_robots/pull/326 should fix the warning about failed serial connection in simulation

**Comment by benmaidel** [comment]
as already in ipa320/cob_robots#326 commented, this is ok!
