### ISSUE TITLE
header files cob_omni_drive_controller

### ISSUE THREAD

**Issue by andreeatulbure** [4am-robotics/cob_driver#327]
Hello,

I tried to extend the cob_omni_drive_controller in order to add a new feature for the raw3-5. I noticed that there are some header files in the src directory of the library (GeomController.h and WheelControllerBase.h). Is there any reason why they are not in the include directory?

Thanks,
Andreea

**Comment by mathias-luedtke** [comment]
> Is there any reason why they are not in the include directory?

The controller headers are for code reuse only, they are not part of the public API.

**Comment by fmessmer** [comment]
@andreeatulbure 
is this issue still relevant? if yes, please open it in cob_control (this is where the `cob_omni_drive_controller` package is located)
Closing!
