### ISSUE TITLE
[cob_mimic] consider c++ implementation

### ISSUE THREAD

**Issue by fmessmer** [4am-robotics/cob_driver#340]
motivated by discussion https://github.com/ipa320/care-o-bot/issues/42#issuecomment-316046500

The ROS release system does not support `python-pip` dependencies...thus, we cannot release `cob_mimic` with a dependency on `python-vlc-pip`.
We should implement `cob_mimic` in C++ using [`libvlc-dev`](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L2987-L2991) which is provided by `apt` which is supported by the ROS release system.

**Comment by floweisshardt** [comment]
@ipa-bnm is investigating what would need to be changed

**Comment by benmaidel** [comment]
It should not be a very big task to port the python code to c++. I think half a day should be enough!
I can do it! It just can take some time till I find half a day off...

**Comment by floweisshardt** [comment]
this is currently blocking the indigo/kinetic release. 
@ipa-bnm please do.
