### ISSUE TITLE
Hydro compile error

### ISSUE THREAD

**Issue by destogl** [4am-robotics/cob_driver#81]
Hello!

When I'm trying to compile hydro version from branch 'hydro_dev' I'm getting following error:

In file included from /home/stogl/Workspace/care-o-bot_hydro_catkin/src/cob_driver/cob_collision_velocity_filter/src/cob_collision_velocity_filter.cpp:50:0:
/home/stogl/Workspace/care-o-bot_hydro_catkin/src/cob_driver/cob_collision_velocity_filter/include/cob_collision_velocity_filter.h:80:73: schwerwiegender Fehler: cob_collision_velocity_filter/CollisionVelocityFilterConfig.h: Datei oder Verzeichnis nicht gefunden
Kompilierung beendet.

I'm not getting this part (and error too) because there doesn't exist CollisionVelocityFilterConfig.h in any branch...

**Comment by mgruhler** [comment]
Hey,

thanks for finding this.

This seems to be a problem with dynamic_reconfigure and catkin.
CollisionVelocityFilterConfig.h is autogenerated from the .cfg file in the folder cfg.

There seems to be a line missing in the CMakeLists.txt, that tells the compiler to generate the config (and thus the header file) before building the node. See [this tutorial](http://wiki.ros.org/dynamic_reconfigure/Tutorials/HowToWriteYourFirstCfgFile#dynamic_reconfigure.2BAC8-Tutorials.2BAC8-HowToWriteYourFirstCfgFile.2BAC8-catkin.Use_the_cfg_File).

There is already a pull-request that will probably fix this for the groovy_catkin branch #80.
If you want, you can try this.

I do not have a machine with hydro set up right now, but I'll test and fix this as soon as I have the time to do so (some time today).

**Comment by destogl** [comment]
Thanks!

Changes in CMakeList.txt made compile successful.
